package org.cf0x.konamiku.data

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/** Structure of update.json generated by GitHub Action */
@Serializable
data class UpdateInfo(
    val version_code: Long,
    val version_name: String,
    val download_url: String,
    val changelog_url: String,
    val latest_changelog: String = ""
)

/** A single commit entry inside changelog-*.json */
@Serializable
data class CommitEntry(
    val hash: String,
    val title: String,
    val body: String = ""
)

/** Structure of changelog-*.json */
@Serializable
data class Changelog(
    val version_name: String,
    val date: String,
    val commits: List<CommitEntry> = emptyList()
)

/** Client-side cached update state */
data class UpdateState(
    val hasUpdate: Boolean = false,
    val latestVersion: String = "",
    val latestCode: Long = 0,
    val downloadUrl: String = "",
    val changelogUrl: String = "",
    val changelog: Changelog? = null,
    val error: String? = null
)

/** Shared Json instance: lenient, ignores unknown keys */
val updateJson = Json { ignoreUnknownKeys = true; isLenient = true }
